name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout code
        uses: actions/checkout@v3

      - name: 🐳 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🔐 Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and Push app1
      - name: 📦 Build and Push app1
        uses: docker/build-push-action@v5
        with:
          context: ./app1
          push: true
          tags: young0319/2025cloud:app1

      # Build and Push app2
      - name: 📦 Build and Push app2
        uses: docker/build-push-action@v5
        with:
          context: ./app2
          push: true
          tags: young0319/2025cloud:app2
